# Generated by Django 5.2.8 on 2025-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeScreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='date_of_birth',
            field=models.DateField(default='2006-10-29'),
        ),
    ]
