# Generated by Django 5.2.8 on 2025-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeScreen', '0002_alter_infomation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomation',
            name='phone_number_field',
            field=models.CharField(default=768768, max_length=255),
            preserve_default=False,
        ),
    ]
